### ISSUE TITLE
ViewabilityHelper is not defined

### ISSUE THREAD

**Issue by rgfx** [outbrain/ViewabilityHelper#1]
pen.js:1 Uncaught ReferenceError: ViewabilityHelper is not defined

Not sure why am getting this error, any help would be great. 

https://codepen.io/rgfx/pen/PEvxgZ?editors=1111

**Comment by lironzluf** [comment]
Hi @rgfx,
ViewabilityHelper is a CommonJS module, used with require or import and therefore requires a module loader such as Webpack or Browserify.
See:
https://stackoverflow.com/questions/19059580/client-on-node-uncaught-referenceerror-require-is-not-defined
