### ISSUE TITLE
ViewabilityHelper is not a constructor

### ISSUE THREAD

**Issue by brianibok** [outbrain/ViewabilityHelper#2]
Getting an error when the code on the example page is used.

Uncaught TypeError: ViewabilityHelper is not a constructor
    at Object.module.exports (example.js:3)
    at __webpack_require__ (bootstrap 6710651afea164dca5b9:19)
    at _typeof (bootstrap 6710651afea164dca5b9:65)
    at bootstrap 6710651afea164dca5b9:65

![image](https://user-images.githubusercontent.com/6074408/35779285-87a1d8ae-0998-11e8-9622-557ab639fd19.png)

https://photos-3.dropbox.com/t/2/AAC4MGgGXl-gATHc-spADn7LEtTKVm_TG7sKfoSP39a2pQ/12/22633370/png/32x32/1/_/1/2/Screenshot%202018-02-04%2010.43.21.png/ENf-gBEYofUiIAIoAg/Jj_mq5LNgyoM4ZM09Gi8RqOsKDc-eGuy1HFbjQVW-h8?preserve_transparency=1&size=2048x1536&size_mode=3

**Comment by lironzluf** [comment]
Thanks @brianibok, can you check now?

**Comment by brianibok** [comment]
Works like a charm. Thanks for the quick update @lironzluf !
